name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    # Only run on PRs if the source branch is on a different repo. We do not need to run everything twice.
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      #with:
        #distribution: 'temurin'
        #java-version: 17
        #check-latest: true
    - name: Build with Gradle
      run: ./gradlew build
