on: [push, pull_request]


jobs:
  gradle:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Run build with Gradle wrapper
      run: ./gradlew build

    - name: Upload Jar
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Build
        path: out/**.jar
